sudo: required
dist: trusty
services:
  - docker
before_install:
  - docker-compose build
install:
  - docker-compose run app npm install
script:
  - docker-compose run app npm run lint
  - docker-compose run app npm test
